ifeq ($(TARGET), Galileo)
	CC=/opt/iot-devkit/1.7.2/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux/i586-poky-linux-gcc
	
else
	CC=gcc

endif


APP = main

all:
	$(CC) -Wall -o $(APP) main.c -lpthread -lm 

clean:
	
	rm -f *.o
	rm -f $(APP) 
